README.md, pyproject.toml, scenario/mocking.py, scenario/runtime.py, scenario/state.py, tests/test_e2e/test_config.py, tests/test_e2e/test_pebble.py, tests/test_e2e/test_vroot.py, tests/test_e2e/test_vroot_resources.py
Fixes #4 
Adds API to control the virtual charm execution root.
For example:
```
my_temp_dir = TemporaryDirectory()
State().trigger(MyCharm, charm_root=my_temp_dir)
```
this will make it so that the charm's `framework.charm_dir` points to that temporary directory. So if the charm were to try and read files from that directory, the test can ensure that they are available, and if the charm were to write files to it, the test can ensure that they are there.
=> Charm resource injection

README.md, scenario/mocking.py, scenario/state.py, tests/test_e2e/test_play_assertions.py, tests/test_e2e/test_relations.py, tests/test_e2e/test_state.py, tests/test_e2e/test_status.py
Fixes #6 
Exposes API to assert that the charm transitioned through a sequence of statuses during its lifetime.
Suppose your charm does:
```python
from ops.model import MaintenanceStatus, ActiveStatus, WaitingStatus, BlockedStatus
def _on_event(self, _event):
self.unit.status = MaintenanceStatus('determining who the ruler is...')
try:
if self._call_that_takes_a_few_seconds_and_only_passes_on_leadership:
self.unit.status = ActiveStatus('I rule')
else:
self.unit.status = WaitingStatus('checking this is right...')
self._check_that_takes_some_more_time()
self.unit.status = ActiveStatus('I am ruled')
except:
self.unit.status = BlockedStatus('something went wrong')
```
You can verify that the charm has followed the expected path by checking the **unit status history** like so:
```python
from …
```
=> Status history

README.md, pyproject.toml, scenario/__init__.py, scenario/consistency_checker.py, scenario/mocking.py, scenario/runtime.py, scenario/state.py, tests/test_consistency_checker.py, tests/test_e2e/test_builtin_scenes.py, tests/test_e2e/test_config.py, tests/test_e2e/test_custom_event_triggers.py, tests/test_e2e/test_play_assertions.py, tests/test_e2e/test_relations.py, tests/test_e2e/test_rubbish_events.py
Added a ConsistencyChecker class responsible for validating the combination of a state, an event, a charm spec, and a juju version.
Upon calling .run(), it performs a series of checks that validate that the state is consistent with itself, with
the event being emitted, the charm metadata, etc...
For example, if someone tries to emit a foo-pebble-ready but there is no container 'foo' in metadata or in State,
this is where we surface the issue.
For the reviewers: 
- does the .run() calling a sequence of check-methods make sense implementation and pattern-wise?
=> Consistency checker

README.md, pyproject.toml, scenario/consistency_checker.py, scenario/fs_mocks.py, scenario/mocking.py, scenario/ops_main_mock.py, scenario/runtime.py, scenario/sequences.py, scenario/state.py, tests/test_consistency_checker.py, tests/test_e2e/test_relations.py, tests/test_runtime.py, tox.ini
This PR addresses several limitations of the existing Relation implementation:
we did not have enough data in the Event datastructure to mock the following relation-event-specific envvars
- `JUJU_UNIT_NAME`
- `JUJU_APP_NAME`
- `JUJU_DEPARTING_UNIT`    -- only for *-relation-departed
This PR adds that functionality and corresponding tests.
We lacked facilities to correctly mock peer and subordinate relation types.
This PR adds two new types: `PeerRelation` and `SubordinateRelation` to address that need.
=> Upgrade to Relation

pyproject.toml, scenario/mocking.py, scenario/state.py, tests/test_e2e/test_pebble.py, tests/test_e2e/test_play_assertions.py, tests/test_e2e/test_state.py, tox.ini
Python 3.11 changed something that broke State's DCBase as it was frequently using other dataclasses as dataclass field default.
Worked around it by freezing all dataclasses in State; some tweaks here and there had to be made to work around the new constraint that all State dataclasses are immutable.
In the future we might want to refactor some flows for the dataclasses to be TRULY immutable instead of working around dataclasse's `__setattr__` check.
=> frozen dataclasses for python 3.11 compatibility

README.md, scenario/context.py, scenario/ops_main_mock.py, scenario/runtime.py, scenario/state.py, tests/helpers.py, tests/test_e2e/test_custom_event_triggers.py, tests/test_e2e/test_juju_log.py
Fixes #38 
Added custom event API:
```python
class FooEvent(EventBase):
pass
class MyObjEvents(CharmEvents):
foo = EventSource(FooEvent)
class MyObject(Object):
my_on = MyObjEvents()
class MyCharm(CharmBase):
def __init__(self, *args, **kwargs):
super().__init__(*args, **kwargs)
self.obj = MyObject(self, "child")
self.framework.observe(self.obj.my_on.foo, self._on_foo)
trigger(
State(),
"foo",
MyCharm,
owner_path=('obj', 'my_on')   # <<<--- this will tell Scenario where to find the event we're trying to emit
)
```
=> [4.0] support for custom events

README.md, pyproject.toml, scenario/consistency_checker.py, scenario/state.py, tests/test_consistency_checker.py, tests/test_e2e/test_relations.py
- added a `RelationBase.NEXT_RELATION_ID` to retrieve the ID the next relation to be instantiated will get
- fixed a bug where the relation ID wouldn't increase
=> public next_relation_id and fix succession

pyproject.toml, scenario/state.py, tests/test_consistency_checker.py, tests/test_dcbase.py
make a deep copy before doing `dataclass.replace` for all objects in `scenario.State`.
=> dedup dcbase.replace

pyproject.toml
Bump PyYAML dependency to 6.0.1 to fix failing builds following release of Cython 3. Also make the requirement less strict to allow users to use newer releases.
=> Bump PyYAML dependency and make it less strict

README.md, pyproject.toml, scenario/runtime.py, scenario/scripts/main.py, tests/helpers.py, tests/test_e2e/test_vroot.py
implemented vroot cleanup:
- scenario now allows metadata.yaml to be present in user-given vroot. if you pass `meta` to `scenario.Context`, metadata.yaml will be overwritten (and when Context is done, it will be restored to its previous state!). Same for actions and config.yaml.
- scenario now cleans up after itself: if it **created** any metadata files, it will delete them.
=> vroot cleanup

pyproject.toml, scenario/runtime.py, scenario/state.py, tests/test_e2e/test_relations.py
Allow
Relation(remote_units_data={}) :
a relation with no remote units.
=> fix error when no remote unit data is passed to relation

pyproject.toml, scenario/mocking.py, tests/test_e2e/test_secrets.py
Highly misleading, currently a different exception is raised by `scenario` than by `ops`, when a secret doesn't exist.
This is cirtical to testing our code, where we need to perform specific actions when a secret is not found, and continue running actions instead of breaking the execution flow
=> SecretNotFoundError should be raised when a secret is not found

.pre-commit-config.yaml, README.md, pyproject.toml, scenario/consistency_checker.py, scenario/mocking.py, scenario/runtime.py, scenario/state.py, tests/test_consistency_checker.py, tests/test_e2e/test_deferred.py, tests/test_e2e/test_event.py, tests/test_e2e/test_event_bind.py, tests/test_e2e/test_network.py, tests/test_e2e/test_rubbish_events.py, tests/test_e2e/test_storage.py, tests/test_runtime.py, tox.ini
This pr fixes a number of error types in `mocking.py` that differed from the ones raised by ops.
Additionally:
- implements the last missing mock: resource-get!
- fly-by-fixes another couple bugs I found
- Fixes #73 
With this, Scenario proper is now feature-complete: all hook tools are mockable.
=> Error types

pyproject.toml, scenario/mocking.py, tests/test_e2e/test_config.py
fixed a bug where config options with falsy default values would not be copied into user-provided config maps
=> fix falsy config defaults

README.md, pyproject.toml, scenario/consistency_checker.py, scenario/mocking.py, scenario/state.py, tests/test_consistency_checker.py, tests/test_e2e/test_network.py
Fixes #87 
This PR adds support for extra-bindings and reworks the network model to hopefully match Juju's more closely.
Issue: at the moment, if you want to add a Network, you always have to pass it in manually:
`State(relations=[rel1, rel2], networks=[net1, net2])`
While in fact the presence of an integration endpoint **implies** the presence of a network. So it feels like a charm should automatically have networks for each of its metadata-defined relation endpoints, regardless of whether the relations are 'alive' i.e. in State.
This PR changes the semantics and the type of `State.networks`: from an exhaustive list of the networks available to the charm being tested, to a binding name --> Network mapping: `State.networks: Dict[str, Network]`
The logic for `network_get(binding:str, …
=> extra bindings and network model rework [Do not merge]

pyproject.toml, scenario/state.py, tests/test_charm_spec_autoload.py
Fixes #92 
Issue:
- the presence of a charmcraft.yaml file confused the code used to determine what version of charmcraft was used to init the charm repo.
Solution:
- make the checks more accurate
=> loosened metadata checks

README.md
I'm pretty sure this is a typo - the text immediately after this example talks about the `container.pebble_ready_event()` being sugar, but the code isn't using it (and also the test doesn't pass as-is, but does with this change).
Also a minor wrapping change, which I think makes it clearer what's happening (that the event is not an argument to `Context`).
=> docs: fix event in README example for pebble-ready

scenario/state.py, tests/test_e2e/test_relations.py, tests/test_e2e/test_state.py
This PR adds the default juju relation keys 
```
DEFAULT_JUJU_DATABAG = {
"egress-subnets": _DEFAULT_IP,
"ingress-address": _DEFAULT_IP,
"private-address": _DEFAULT_IP,
}
```
To all unit databag default values in Relation, SubordinateRelation and PeerRelation.
=> Default data in databags

README.md, pyproject.toml, scenario/ops_main_mock.py, tests/test_e2e/test_relations.py
=> ops 2.10 relation broken behaviour fix

scenario/runtime.py, scenario/sequences.py, scenario/state.py, tests/test_context.py, tests/test_e2e/test_actions.py
Sets `JUJU_ACTION_UUID` when handling an action event, so that `ops` sets `ActionEvent.id` appropriately. The ID is loaded from `state.next_action_id` and set on the `state.Action` object, similarly to relations.
Also stops setting `JUJU_ACTION_NAME` outside of action events - mostly to simplify the code addition, but in my quick checks this is the case in Juju as well.
Fixes #101
=> feat: add support for ActionEvent.id

pyproject.toml, scenario/ops_main_mock.py
charms that pin ops to <2.10 will have trouble with the breaking_relation_id args that scenario passes indiscriminately to ops.Model
=> Older ops compat

scenario/state.py
Currently, Scenario defaults `Model.name` and `Model.uuid` to the same (random) value across all instances. This PR changes the class to use a `dataclasses.field` `default_factory` instead, so that each instance gets a unique (random) default.
=> fix: use default_factory to provide default UUID and name values for Model

README.md
A collection of a few improvements to the README:
* "juju" to "Juju" where it's talking about the product and not the CLI
* "scenario" to "Scenario" where it's talking about the product
* Some heading adjustments - I think this matches what the outline was going for, where parts of state are all under the state top-level and are equally at the same level
* `import ops` rather than `from ops import` - this is what the Charm Tech team are recommending, so it's nice to have it here too
* `import scenario` rather than `from scenario import` - because we got a very reluctant "ok" when we proposed this :smile: 
* Fix the example that has the final status in the status history, even though it says right afterwards that that doesn't happen
* Explicit `framework` in `__init__`, again to match …
=> docs: minor tidying up of the README

scenario/consistency_checker.py, tests/test_consistency_checker.py, tests/test_e2e/test_config.py
Some small corrections to the consistency checker's validation of the `type` field in config:
1. "integer" is not valid (at least in Juju 3.4.0), so remove it
2. "number" is not valid (at least in Juju 3.4.0), so remove it
3. "float" is missing, so add it
4. This is currently undocumented (that should be fixed soon) but "type: secret" is valid from Juju 3.4 onwards, so add it (conditionally on the Juju version)
Adjust tests to match.
See also canonical/operator#1166 for `type:secret` issue in `Harness`.
=> fix: correct the consistency checker's config "type" validation

scenario/ops_main_mock.py
This code currently has no output, but does fail:
<details>
<summary>example code</summary>
```python
import ops
import scenario
class MyCharm(ops.CharmBase):
def __init__(self, framework):
super().__init__(framework)
framework.observe(self.on.config_changed, self._on_config_changed)
def _on_config_changed(self, event):
self.unit.get_container("example").replan()
ctx = scenario.Context(
MyCharm,
meta={"name": "my-charm", "containers": {"example": {"resource": "ubuntu-22.04"}}},
)
container = scenario.Container("example", can_connect=False)
state = scenario.State(containers=[container])
out = ctx.run("config-changed", state=state)
```
</details>
```
$ python /tmp/scenario-102.py ; echo $?
1
```
This PR resets the `sys.excepthook` change that ops does (to redirect output to Juju's …
=> Reset sys.excepthook.

tox.ini
[pyproject.toml](pyproject.toml) specifies that the minimum Python version is 3.8, so it doesn't seem to make sense to test against 3.6 or 3.7. Presumably, Scenario should support the same Python versions as ops, which is (I believe) a minimum version of the Python included with the oldest LTS still in standard support (so Python 3.8 in 22.04 until April 2025).
Add in tests against 3.12, since it seems reasonable for people to be using Python 3.12, and we'd want to know about breakage earlier rather than later anyway.
=> chore: drop tests for Python 2.6, 2.7, add 3.12

scenario/consistency_checker.py, scenario/runtime.py, scenario/state.py, tests/test_consistency_checker.py
* Check that there aren't StoredState objects in the state that apply to the same attribute on the same object
* Check that the StoredState object doesn't contain types that ops would not be able to store in Juju
* Make the `_data_type_name` attribute private
=> feat!: add basic StoredState consistency checks

README.md, scenario/__init__.py, scenario/consistency_checker.py, scenario/mocking.py, scenario/state.py, tests/test_consistency_checker.py, tests/test_e2e/test_cloud_spec.py
Add support for cloud spec with an e2e test.
=> feat: add support for cloud spec

README.md
PyPI uses a proxy (Camo) to serve images in a more secure way. This ensures that the images are served over HTTPS, even if the original source is not. However, the original image URL still needs to be accessible publicly for this to work correctly.
=> docs: fix state transition image on PyPI

.github/workflows/quality_checks.yaml
This should get reverted prior to (or just after) merging to main, but it would be handy to avoid the 7.0 branch getting into a bad state.
=> ci: temporarily enable CI quality checks for the 7.0 branch

.pre-commit-config.yaml
Bumps the version of the add-trailing-comma hook tool to the latest, to avoid this:
```
tameyer@tam-canoncial-1:~/code/ops-scenario$ grep 'def storage_add' -A 5 scenario/mocking.py 
def storage_add(self, name: str, count: int = 1):
if not isinstance(count, int) or isinstance(count, bool):
raise TypeError(
f"storage count must be integer, got: {count} ({type(count)})",
)
tameyer@tam-canoncial-1:~/code/ops-scenario$ pre-commit run --files scenario/mocking.py add-trailing-comma > /dev/null
tameyer@tam-canoncial-1:~/code/ops-scenario$ grep 'def storage_add' -A 5 scenario/mocking.py 
def storage_add(self, name: str, count: int = 1):
if not isinstance(count, int) or isinstance(count, bool):
raise TypeError(
f"storage count must be integer, got: {count} ({type(count)},
)",
)
```
=> chore: update the add-trailing-comma hook

.pre-commit-config.yaml, README.md, tests/readme-conftest.py, tox.ini
Adds a tox environment `test-readme` (not run by default) that tests (most of) the code blocks in [README.md](README.md).
Also some corresponding changes to the README:
* Remove all the `import ops` and `import scenario` lines - these seem like noise and are implied I think.
* Remove "from charm import Charm" type lines and "class MyCharm(...): ..." lines - these also seem like noise, although they are a little bit less implied. I could add a "here is the code that's used throughout the doc" section at the top if that would be better.
* Flesh out a couple of examples a small amount so that the various asserts work.
* Fix a few bugs that had crept in (the kind of ones that running this tox command would catch).
=> test: test the code in the README

pyproject.toml
What do you think?
Or maybe `7.0.0b1` or just mark it dynamic for now?
=> Mark upcoming branch as dev or beta version

pyproject.toml, scenario/runtime.py, scenario/state.py, tests/test_e2e/test_event.py, tests/test_e2e/test_secrets.py
Fixes the `secret-remove` event name and sets the `JUJU_SECRET_REVISION` environment variable for rotate and expired events. Adds a basic test that each type of secret event can be emitted.
There's a more significant revamp of secret events coming in 7.x but this fixes the core issues for 6.x.
Fixes #157.
=> fix: fix secret-remove and secret-expired events

.gitignore, README.md, docs/custom_conf.py, scenario/__init__.py, scenario/consistency_checker.py, scenario/context.py, scenario/state.py, tests/test_consistency_checker.py, tests/test_context.py, tests/test_context_on.py, tests/test_e2e/test_actions.py, tests/test_e2e/test_manager.py
This adjusts emitting action events to align with emitting other events.
When needing to pass params, instead of having to create an `Action` object, these can just be passed in the run call in the same way that extra parameters for notices, relations, etc are. When using params, the code is about the same size - when there are no parameters it's a little longer than just having a string, but much more consistent, both with the other events, and with using observe.
Example:
```python
ctx = Context(MyCharm)
ctx.run(ctx.on.start(), State())
ctx = Context(MyCharm)
ctx.run(ctx.on.action("foo"), State())
ctx = Context(MyCharm)
ctx.run(ctx.on.action("foo", params={"bar": 123}), State())
```
=> feat!: make action events more like other events

.gitignore, docs/custom_conf.py, scenario/state.py
This changes the signature for `State` but the actual implementation stays the same:
* You can pass any iterable (e.g. tuple, list, set) for the collections of things in State (relations, containers, etc)
* The state "freezes" whatever you pass into a frozenset, which is what you get if you do e.g. `State.relations`
The advantage of this change is that without it, if you do:
```python
State(containers={container})
```
Then type checkers will complain with something like `Argument of type "set[str]" cannot be assigned to parameter "x" of type "frozenset[str]" in function "__init__" "set[str]" is incompatible with "frozenset[str]" (reportArgumentType)`.
The main disadvantage is that the auto-generated reference docs can't tell that the `__post_init__` conversion happens, so can only say …
=> fix: state components take an Iterable rather than a frozenset

README.md, pyproject.toml, scenario/__init__.py, scenario/consistency_checker.py, scenario/context.py, scenario/mocking.py, scenario/runtime.py, scenario/state.py, tests/test_consistency_checker.py, tests/test_e2e/test_deferred.py, tests/test_e2e/test_pebble.py, tox.ini
Adds support for the {container-name}-pebble-check-failed and {container-name}-pebble-check-recovered events that will be available in Juju 3.6.
Example usage:
```python
ctx = Context(MyCharm)
check_info = CheckInfo("http-check", failures=7, status=ops.pebble.CheckStatus.DOWN)
container = Container("my-container", check_infos={check_info})
state = State(containers={container})
ctx.run(ctx.on.pebble_check_failed(container=container, info=check_info), state)
```
Also updates the support for Pebble custom notice events to align with the 7.x approach (event from ctx.on, notices are a frozenset).
Updated usage:
```python
ctx = Context(MyCharm)
notices = [
Notice(key="example.com/a", occurrences=10),
Notice(key="example.com/b", last_data={"bar": "baz"}),
Notice(key="example.com/c"),
]
container …
```
=> feat: add support for Pebble check events

README.md, scenario/mocking.py, scenario/state.py, tests/test_consistency_checker.py, tests/test_e2e/test_network.py, tests/test_e2e/test_state.py
This moves the default Network into the `Network` initialisation, rather than as a separate classmethod that provides a `Network` object. This is more consistent with the rest of the Scenario objects, which try to have useful defaults where possible.
For the most simple case:
```python
network = Network.default()
network = Network("default")  # The name is needed because of the `State` change elsewhere
```
To override elements of the default is a little bit more work, particularly if it's in the nested `Address` object, but it doesn't seem too bad:
```python
network = Network.default(private_address="129.0.2.1")
network = Network("foo", [BindAddress([Address("129.0.2.1")])])
```
=> feat!: move default network into Network()

pyproject.toml, scenario/consistency_checker.py, scenario/mocking.py, tests/test_e2e/test_network.py
Special-cases network-get for the `juju-info` relation so that it won't raise if no binding with that name is found in the charm metadata.
User can still override the network by passing it to `State.networks`.
Fixes #164
=> fixed juju-info network

scenario/mocking.py, scenario/state.py, tests/test_e2e/test_secrets.py
When we get a secret and provide both ID and label, the label should update to the provided one. This was previously missing in Scenario.
Fixes #95
=> fix: update secret label when getting with both id and label

README.md, scenario/__init__.py, scenario/state.py, tests/test_e2e/test_deferred.py
A couple of changes to simplify setting up the queue of deferred events:
* Adjusted the docs for `DeferredEvent` to strongly suggest that it's for internal use only and people should use the `.deferred()` method of an `_Event` instead. It's still required internally (to go to/from the ops state) and might be needed in obscure cases, but this reduces the number of ways people need to be aware of by one.
* The `scenario.deferred()` helper is removed. When using this method for events that link to components (relations, containers, etc) it was possible to not have the event set up correctly, and it didn't really seem to offer much over `.deferred()`. Removing it leaves one normal way to create deferred events.
Finally, setting up the `DeferredEvent` snapshot data only handled workload events …
=> feat!: simplify creating deferred events

.vscode/settings.json, pyproject.toml, scenario/ops_main_mock.py
The next release of ops has some backwards-incompatible changes to private methods. This PR does the minimum to keep Scenario working with the current version of ops and the next release.
I'll open a ticket for doing a nicer version of this where the new `_JujuContext` class is used (which would presumably mean requiring the new version of ops). But this will let people continue upgrading their ops as long as they're using the latest 6.x of Scenario.
The relevant ops PR is: https://github.com/canonical/operator/pull/1313
=> chore: add compatibility with the next ops release

.gitignore, scenario/context.py, scenario/state.py
* Remove `Manager.output` as noticed by @PietroPasotti 
* If `Context.run_action` is called, raise an error but point them towards the solution.
* If `Context.run` is called with a string or callable event, raise an error but point them towards the solution
* If `Relation.relation_id` is used, raise an error but point towards `.id`
=> chore: add some code to ease the transition from 6.x to 7.0

pyproject.toml, scenario/ops_main_mock.py
This hopefully avoids needing to do a 6.1.x release to fix compatibility with any upcoming ops release.
=> chore: limit Scenario 6 to use ops 2.12-2.16

pyproject.toml, scenario/state.py
Python 3.9 changes the behaviour of `inspect.signature` - in 3.8 if a class has a parent with a `__new__` then the `__new__` is used when getting the class signature, and in 3.9 (and above) the class's `__init__` is used.
Instead of getting the class's signature, get the signature of `__init__` explicitly (ignoring `self`), so that this works in 3.8 as well as 3.9 and above.
I've done `uvx --python=3.{8,9,10,11,12} tox -e unit` , so things should be good now.
Fixes #187
=> fix: adjust the inspect.signature behaviour to work with Python 3.8

pyproject.toml, scenario/mocking.py, scenario/ops_main_mock.py
The `Secret._canonicalize_id` method requires the model UUID to be passed in ops:main@HEAD.
There are some names that have moved from `ops.main` to `ops._main` - they are re-exported so Scenario doesn't actually break, but the static check complains if they are imported from `ops.main`.
This handles both current ops and ops 2.17 so that it can be merged ahead of the ops release, but the backwards compatibility should just get dropped and the minimum ops version bumped after the release, I think.
=> chore: handle the changes coming in ops 2.17

pyproject.toml, scenario/mocking.py, tests/test_e2e/test_relations.py
`State.get_relation` raises `KeyError` when no matching relation can be found, so adjust the mocking to expect that rather than `ValueError` as previously.
Add a test that validates the various results of `ops.Model.get_relation` when the relation doesn't exist.
Fixes #193
=> fix: ops.Model.get_relation should not raise when a relation with the specified ID does not exist

pyproject.toml
Having this file available makes pyright happier when checking code that imports Scenario.
=> chore: add py.typed file

scenario/context.py, scenario/state.py
One typo, one set of docs that have moved.
I haven't bumped the version number, which I think means that the release workflow just fails and there's no new release and all is well? This doesn't seem like it really needs a separate release. But if that causes bad things to happen, I can add that of course.
=> docs: fix incorrectly copied docstring, update Pebble docs link

pyproject.toml, scenario/state.py
Adjust `AnyJson` so that the type of the nested list/dict is also defined.
This should avoid errors like this:
```
/home/tameyer/code/operator/test/test_testing.py
/home/tameyer/code/operator/test/test_testing.py:7060:17 - error: Type of "action" is partially unknown
  Type of "action" is "(name: str, params: Mapping[str, str | bool | dict[Unknown, Unknown] | int | float | list[Unknown]] | None = None, id: str | None = None) -> _Event" (reportUnknownMemberType)
1 error, 0 warnings, 0 informations 
```
=> feat: use a slightly more strict type for `AnyJson`

scenario/__init__.py
I'm pretty sure this was left out by mistake rather than for any other reason.
=> feat: expose CharmEvents at the top level
